name: Python application test with Github Actions
on:
  push:
    branches:
    - master
    paths:
    - 'C2-AgileDevelopmentwithAzure/project/**'

  workflow_dispatch:

jobs:
  
  build:
    # platform
    runs-on: ubuntu-latest

    # checks out runner
    steps:
    - uses: actions/checkout@v2
    # error on 3.5
    - name: Set up Python 3.10.13
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.13

    - name: run pip
      run: |
        cd "C2-AgileDevelopmentwithAzure/project/starter_files/flask-sklearn"
        make install
      
    - name: run lint
      run: |
        cd "C2-AgileDevelopmentwithAzure/project/starter_files/flask-sklearn"
        make lint
      
    - name: run pytest
      run: |
        cd "C2-AgileDevelopmentwithAzure/project/starter_files/flask-sklearn"
        make test
